AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'cookbooks/*/.kitchen/*'

LineLength:
  Max: 99

MethodLength:
  Max: 30

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

ClassAndModuleChildren:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
