default['proxysql']['pre_statements'] = [
  'LOAD MYSQL USERS FROM CONFIG',
  'LOAD MYSQL USERS TO RUNTIME',

  'LOAD MYSQL SERVERS FROM CONFIG',
  'LOAD MYSQL SERVERS TO RUNTIME',

  'LOAD MYSQL QUERY RULES FROM CONFIG',
  'LOAD MYSQL QUERY RULES TO RUNTIME',

  'LOAD MYSQL VARIABLES FROM CONFIG',
  'LOAD MYSQL VARIABLES TO RUNTIME',

  'LOAD ADMIN VARIABLES FROM DISK',
  'LOAD ADMIN VARIABLES FROM CONFIG',
  'LOAD ADMIN VARIABLES TO RUNTIME'
]
